environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"
build: off
test_script:
  - node --version
  - npm --version
  - npm run test
version: "{build}"